logging:
  level:
    org.springframework.web: "INFO"

currencylayer:
  api:
    accesskey: aaf13c95d3b6669707e8d2af72ac82b5
    endpoint: apilayer.net
    
spring:
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    
