server:
  port: 8081
configuration:
  properties:
    language: "DE"
logging:
  level:
    org.springframework.web: "INFO"
spring:
  cloud:
    config:
      refresh:
        rate: 30
        timeUnit: SECONDS