logging:
  level:
    org.springframework.web: "ALL"
spring:
  cloud:
    config:
      refresh:
        enabled: false
  consumers:
    concurrency: 2
  jobs:
    jobs:
      restart:
        interval: 10
        timeunit: "SECONDS"
