logging:
  level:
    org.springframework.web: "INFO"
spring:
  cloud:
    config:
      refresh:
        enabled: false
  jobs:
    jobs:
      restart:
        interval: 10
        timeunit: "SECONDS"
